import type { Metadata } from "next";
import { Onest } from "next/font/google";
import "./globals.css";
import { Toaster } from "sonner";

const onest = Onest({
  subsets: ["latin", "cyrillic"], // шрифт поддерживает кириллицу!
  variable: "--font-onest",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={` ${onest.variable} antialiased`}>
        {children}
        <Toaster
          position="bottom-left"
          richColors
          closeButton
          duration={5000}
          toastOptions={{
            classNames: {
              toast: "rounded-[20px]",
              title: "text-[#0B0911] font-semibold",
              description: "text-[#8F8F92]",
              actionButton: "rounded-[12px] border border-[#D9D9DE] px-4 py-2",
              closeButton: "text-[#8F8F92]",
            },
          }}
        />
      </body>
    </html>
  );
}
